# -*- coding: utf-8 -*-
"""hate word detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MBlhMZCAtsAvk6_57nbHF2aRg7xvxV3T
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('My Drive')

os.listdir()

negative=open("negative-words.txt",'r',encoding = "ISO-8859-1")
train=[]
test=[]
negative_count=0
positive_count=0

j=0
for i in negative:  
  if(j%2!=0):
    if(j%3==0):
      train.append((i[-len(i):-1],'neg'))
    else:
      test.append((i[-len(i):-1],'neg'))  
    negative_count+=1       
  j+=1 
   

k=0  
positive=open("positive-words.txt",'r',encoding="ISO-8859-1")  
for i in positive:  
  if(k%2==0):
    train.append((i[-len(i):-1],'pos'))
  else:
    test.append((i[-len(i):-1],'pos'))
  k+=1 
  positive_count+=1

print(negative_count)
print(positive_count)
import random
random.shuffle(test)
random.shuffle(train)

!pip install textblob

from textblob.classifiers import NaiveBayesClassifier

import nltk
nltk.download('punkt')

cl = NaiveBayesClassifier(test)

cl.accuracy(train)

print(cl.classify("you are an amazing baby"))
print(cl.classify("i will kill you"))
print(cl.classify("lets go out for a walk"))
print(cl.classify("you are such a gooood baby "))

